- name: download Glassfish
  get_url: url=http://download.java.net/glassfish/4.1.2/release/glassfish-4.1.2.zip dest=/root/glassfish-4.1.2.zip

- name: unpack Glassfish
  unarchive: remote_src=True src=/root/glassfish-4.1.2.zip dest=/opt

- name: create a user
  user: name={{ glassfish_user }}

- name: set permissions
  file: state=directory recurse=yes dest=/opt/glassfish4/glassfish/domains/domain1 owner={{ glassfish_user }} group={{ glassfish_user }}

- name: put systemd unit file to its destination
  template: src=glassfish.service dest=/etc/systemd/system/glassfish.service owner=root group=root mode=0644
  notify: systemctl daemon-reload

- name: enable glassfish service
  service: name=glassfish enabled=yes state=started
